# Generated by Django 4.1.4 on 2022-12-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('progress', models.TextField(verbose_name='Прогресс')),
                ('max_point', models.TextField(verbose_name='Максимальный балл')),
                ('theory', models.TextField(verbose_name='Теория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Номер')),
                ('type', models.TextField(verbose_name='Тип')),
                ('point', models.TextField(verbose_name='Балл')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('picture', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.course')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='TaskStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(verbose_name='Правильность решения')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.task')),
            ],
            options={
                'verbose_name': 'Статистика задания',
                'verbose_name_plural': 'Статистика заданий',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.student')),
            ],
            options={
                'verbose_name': 'УченикКурс',
                'verbose_name_plural': 'УченикиКурсы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='class.student')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.student')),
            ],
            options={
                'verbose_name': 'РодительУченик',
                'verbose_name_plural': 'РодителиУченики',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_right', models.BooleanField(verbose_name='Правильный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.task')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
