# Generated by Django 4.1.4 on 2022-12-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_delete_pizdos_alter_child_id_alter_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('login', models.TextField(verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
    ]
